INSERT INTO ADMIN_TABLE(EMAIL, PASS) 
VALUES ('martinelidantes232@gmail.com', 'Atos123$');

INSERT INTO CATEGORY_TABLE(CATEGORY_NAME) 
VALUES ('Devices');
INSERT INTO CATEGORY_TABLE(CATEGORY_NAME) 
VALUES ('Consoles');
INSERT INTO CATEGORY_TABLE(CATEGORY_NAME) 
VALUES ('Monitors');

INSERT INTO PRODUCT_TABLE(PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAILABLE_QTY)
values('Monitor 27 inc', 'C00025', 10000.00, 'monitor.png', 10 );

INSERT INTO PRODUCT_TABLE(PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAILABLE_QTY)
values('keyboard white', 'C00026', 1500.00, 'keybaord_white.png', 200 );

INSERT INTO PRODUCT_TABLE(PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAILABLE_QTY)
values('PlayStation 5', 'C00023', 45500.00, 'ps4.png', 2 );

INSERT INTO PRODUCT_TABLE(PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAILABLE_QTY)
values('Mouse', 'C00026', 500.00, 'mouse.png', 2 );

